### ISSUE TITLE
Unexpected indent when annotating arguments in python

### ISSUE THREAD

**Issue by AckslD** [yioneko/vim-tmindent#1]
Consider the following code:
```python
def h(a, b):
    pass


def f(a|, b):
    pass
```
where `|` is the cursor. If I press `:` to start typing an annotation I get:
```python
def h(a, b):
    pass


    def f(a:, b):
    pass
```
note that this does not happen for the first function in the module (eg `h` in this case).

**Comment by yioneko** [comment]
For now you can simply `:set indentkeys-=<:>` to fix this specific problem. I tested with vscode, it seems that they only fix this behavior for `pass` statement. I'll take a deeper look for this.

**Comment by AckslD** [comment]
Thank you @yioneko, that indeed solves this issue

**Comment by yioneko** [comment]
You can now keep `indentkeys` settings without touch and also make this indent case works well. The new fix targeted at python only, for any similar case like:

```python
def foo(a):
  if True:
    while True:
      # any following indent less than 3xshift will be kept as is
      # if True:
    # if True: 
  # if True:
``` 

BTW in VSCode, they only apply indent rules on blank new line, and never encounter such issues triggered by `indentkeys`. If you want the same experience, just reset that option. Controlling `indentkeys` is currently considered out of scope of this plugin.

**Comment by AckslD** [comment]
Thank you @yioneko! Can confirm it works for me and makes indeed sense that this plugin does not control `indentkeys` (I still need to actually read a bit more about this option to understand exactly how it works).
